---
# Defines deployment design and assigns role to server groups

- hosts: mons
  become: True
  roles:
  - ceph-mon

- hosts: agents
  become: True
  roles:
  - ceph-agent

- hosts: osds
  become: True
  roles:
  - ceph-osd

- hosts: mdss
  become: True
  roles:
  - ceph-mds

- hosts: rgws
  become: True
  roles:
  - ceph-rgw

- hosts: restapis
  become: True
  roles:
  - ceph-restapi

- hosts: rbdmirrors
  become: True
  roles:
  - ceph-rbd-mirror

- hosts: nodes
  user: vagrant
  roles:
    - role: marvinpinto.docker
      sudo: true
    - role: ClusterHQ.flocker
      flocker_cluster_name: my_flocker_cluster
      flocker_api_cert_name: plugin
      flocker_install_docker_plugin: true
      flocker_local_tempdir: "{{ playbook_dir }}/certs"
